### ISSUE TITLE
Arrays now supported in RRF 3.5.0 beta 2

### ISSUE THREAD

**Issue by BladerunnerxRC** [owendare/RepRapFirmware-Macros#1]
Love your scripts. Present modifying for RailCore2

**Comment by owendare** [comment]
Yes, I am aware that arrays are now supported.
There are  couple of macros that now use them.
Calibrate BLTouch is one.

**Comment by BladerunnerxRC** [comment]
I'm running through your scripts now for my installation on a RailCore2.
I'm about ready to test.
